### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [ecipra/teacozy#5]
**GRADE**: Exceeds Expectations

**SUMMARY**: Great work on this project. Once a couple of the resources were linked back up, the site was looking awesome. Great work keeping your project folder and the html and css neat, organized, and readable as well. Also, beautiful use of flex display to help align items throughout the page!

There isn't much to say as far as improvements to be made to the site. Fix up those two links I mentioned and you should be all set!

Nice job using some subtle hover effects in the nav section. Try taking a peek through some of [this info](https://css-tricks.com/almanac/properties/a/animation/) on css animation to see if there's anything that piques your interest. 

Have fun and keep up the great work!

**Comment by ecipra** [comment]
Awesome—thanks for the review! Will also check out the animation a bit more—very keen to dive into that where possible.
